---
title: "3-data-visualization"
output: html_document
author: "Abel Rodríguez"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(gapminder)
library(ggplot2)
```

## Data visualization
### 3.0.1 Variable assignment

```{r}
  gapminder_1952 <- gapminder %>% filter(year == 1952)
  gapminder_1952
```

### 3.0.2 Comparing population and GDP per capita
```{r}
  gapminder_1952 <- gapminder %>% filter(year == 1952)  
  ggplot(gapminder_1952, aes(x = pop, y = gdpPercap)) + geom_point()
```

### 3.0.3 Comparing population and life expectancy

```{r}
  gapminder_1952 <- gapminder %>% filter(year == 1952)
  
  ggplot(gapminder_1952, aes(x = pop, y = lifeExp)) + geom_point()
```

### 3.0.4 Putting the x-axis on a log scale

```{r}
gapminder_1952 <- gapminder %>%
  filter(year == 1952)

# Change this plot to put the x-axis on a log scale
ggplot(gapminder_1952, aes(x = pop, y = lifeExp)) +
  geom_point() +
  scale_x_log10()
```

### 3.0.5 Putting the x- and y- axes on a log scale
```{R} 
gapminder_1952 <- gapminder %>%
  filter(year == 1952)

# Scatter plot comparing pop and gdpPercap, with both axes on a log scale
ggplot(gapminder_1952, aes(x = pop, y = gdpPercap)) +
  geom_point() +
  scale_x_log10() +
  scale_y_log10()
```

### 3.0.6 Adding color to a scatter plot
```{R}
gapminder_1952 <- gapminder %>% filter(year == 1952)


# Scatter plot comparing pop and lifeExp, with color representing continent
ggplot(gapminder_1952, aes(x = pop, y = lifeExp, color = continent)) +
  geom_point() +
  scale_x_log10()
```

### 3.0.7 Adding size and color to a plot
```{R}
gapminder_1952 <- gapminder %>% filter(year == 1952)


# Scatter plot comparing pop and lifeExp, with color representing continent
ggplot(gapminder_1952, aes(x = pop, y = lifeExp, color = continent, size = gdpPercap)) +
  geom_point() +
  scale_x_log10()
```

### 3.0.8 Creating a subgraph for each continent
```{R}
  gapminder_1952 <- gapminder %>% filter(year == 1952)

  # Scatter plot comparing pop and lifeExp, faceted by continent
  ggplot(gapminder_1952, aes(x = pop, y = lifeExp)) +
    geom_point() +
    scale_x_log10() +
    facet_wrap(~ continent)
```

### 3.0.9 Faceting by year
```{R}
  ggplot(gapminder, aes(x = pop, y = lifeExp, color = continent, size = gdpPercap)) +
    geom_point() +
    scale_x_log10() +
    facet_wrap(~ year)
```